### ISSUE TITLE
Test failure details are unavailable

### ISSUE THREAD

**Issue by j-troc** [sillsdev/icu-dotnet#109]
The link with test failure details for PR is inaccessible.
Could these results be shared?

**Comment by ermshiperete** [comment]
Yes, that's the plan eventually. Unfortunately the project to create a publicly accessible Jenkins instance that would allow this moves very slowly. And the solution we had in the past of building on a private Jenkins and then publishing to a publicly visible one is no longer viable due to hardware problems.

**Comment by ermshiperete** [comment]
We're using GHA now instead of Jenkins, so the build and test results are visible.
