### ISSUE TITLE
[Question] Features for icu.net

### ISSUE THREAD

**Issue by conniey** [sillsdev/icu-dotnet#14]
Hi,

I am currently migrating [Lucene.NET to .NET Core](https://github.com/apache/lucenenet/pull/191) and as a part of that, use icu.net. The other .NET icu4c library uses a Managed C++ wrapper, so your project is the most feasible for compiling/running on .NET Core. (Couchbase-lite, Orchard CMS and a few other projects are also considering using your library when they move to .NET Core.)

* Would you be OK with creating an icu.net package that contains the full 22MB binaries?
* Are you interested in creating a single NuGet package that targets x64 and x86. I've [utilised logic](https://github.com/conniey/icu-dotnet/blob/migrateToNetStandard/source/icu.net/NativeMethods.cs#L91-L105) from libgit4sharp to add the right paths when loading the native binaries.
* Interest in migrating this library to and releasing .NET Core package on NuGet.org

I've already done the work, but I wanted to get your consent before I add a PR because it would require your build server to have Visual Studio 2015 (Community or higher).

**Comment by ermshiperete** [comment]
@conniey Yes, a PR would be welcome.

I'm currently in the process of refactoring our icu.net nuget package. A recent change on master dynamically loads the ICU libraries and so removes the need of maintaining a separate version of icu.net for each ICU version. As part of refactoring the nuget packaging I'll move the unmanaged ICU binaries to a separate nuget package. We could create a separate nuget package that contains the full ICU binaries.

It's a good idea to have the nuget package target both x64 and x86 - so far we didn't have a need for that so we applied YAGNI, but I'm happy to change that. (A PR would be welcome since currently I'm not sure how to build for both x64 and x86 and then create a nuget package of it - might be easy, just haven't dealt with that before).

We're definitely interested in migrating to .NET Core.

Thanks for your suggestions and contributions!

**Comment by conniey** [comment]
@ermshiperete I was trying to add logic to load either x86 or x64 native libraries at runtime and was wondering if there was a public repository you use to build `Icu4c.Win.*`.  I want to modify the package structure and how it includes the native binaries to support NuGet v3 as well as existing NuGet v2.

**Comment by ermshiperete** [comment]
@conniey That's done in the `*StaticallyLinked*` branches of https://github.com/sillsdev/icu4c
