### ISSUE TITLE
 System.DllNotFoundException: Unable to load shared library 'libdl.so' on Ubuntu 22.04

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/icu-dotnet#186]
## Describe the bug

ICU.NET crashes on Ubuntu 22.04 when trying to load ICU, because "libdl.so" cannot be found. "libdl.so" no longer exists on Ubuntu 22.04. You must use "libdl.so.2".

## To Reproduce

1. Call any ICU.NET method on Ubuntu 22.04

## Expected behavior

The code should not throw an exception.

## Environment

- OS: Ubuntu 22.04
- Exact version of icu.net: 2.8.1
- .NET Framework/Core version: .NET 6

**Comment by ddaspit** [comment]
I can see that there is a `icu.net.dll.config` file that should properly define the mapping for Ubuntu 22.04. Maybe we aren't deploying that file properly.

**Comment by ermshiperete** [comment]
There are two problems with the combination of Ubuntu 22.04 and .NET 6: 
a) Ubuntu 22.04 no longer ships a -dev package that brings the `libdl.so` file (which hides the fact that the the `icu.net.dll.config` is missing or not working)
b) .NET Core and .NET 5+ no longer support the dll mapping mechanisms in the `.config` files that Mono introduced.

icu.net 2.9.0 implements it's own `.config` file handling so that it will continue to work with .NET 6.

See #181  and #185.

**Comment by ermshiperete** [comment]
Fixed in **icu.net 2.9.0**.

**Comment by ddaspit** [comment]
Thanks. I think we got it working.

**Comment by rmunn** [comment]
Just experienced this with a fresh install of Ubuntu 24.04 (specifically, Linux Mint 22, which uses Ubuntu 24.04 as a base). To reproduce:

* Install a fresh copy of Ubuntu 24.04 (or [Linux Mint 22](https://blog.linuxmint.com/?p=4725) if Ubuntu 24.04 doesn't repro) in a virtual machine
* Run `apt update; apt upgrade -y` to make sure all packages are up-to-date
* Run `apt install dotnet-sdk-8.0`
* Clone https://github.com/sillsdev/web-languageforge/
* `cd backend/FwLite/LocalWebApp`
* Run `dotnet build`. Build succeeds.
* Run `dotnet watch`. Note the many `libdl.so: cannot open shared object file: No such file or directory` errors.
