### ISSUE TITLE
Any plans to support the new Normalizer2/unorm2.h API?

### ISSUE THREAD

**Issue by NightOwl888** [sillsdev/icu-dotnet#48]
I am porting over parts of Lucene that utilize ICU4J, and noticed that while Collator seems mostly complete, we are missing the new [Normalizer2 API](http://userguide.icu-project.org/transforms/normalization), which maps to the [unorm2.h API in C](http://www.icu-project.org/apiref/icu4c/unorm2_8h.html#a31dd7a1489513e940da239921265da32).

In fact, I don't see what advantage the Normalizer in this package has over `string.Normalize(NormalizationForm)` and `string.IsNormalized(NormalizationForm)` in .NET (which seems to make it rather pointless).

Specifically, what I am interested in are:

1. NFKC_Casefold
2. spanQuickCheckYes
3. FilteredNormalizer2 
4. `.nrm` Binary Data File Support

Do you have any plans on supporting this? If not, what are your guidelines for contributing?

**Comment by NightOwl888** [comment]
Just wondering if anyone is still interested in running this project? 

We have icu.net as a dependency to Lucene.Net and need the above mentioned feature and a couple of other features ported and we have also found some bugs that need patching. There are a few people on our end who can do the work, but we need someone on your end to review and release our commits. I'd like to try to avoid creating a fork and separate NuGet package if at all possible.

One thing that is a bit of a thorn is the current lack of official .NET Standard support, which #37 would fix if it were only made into a pre-release on NuGet.

If you don't have anyone available to help us release, could you please give one of our team members (such as @conniey) access?

**Comment by ermshiperete** [comment]
> Just wondering if anyone is still interested in running this project?

@NightOwl888 Sorry for the long delay in replying - I've been away on vacation. We're definitely still interested in running this project, but we're pretty limited in our resources, and this project is not the only responsibility I have. #37 requires some changes to our infrastructure since Mono 5 which allows to build #37 isn't available in the default Ubuntu repos. It's on my to-do list and I'll work on it ASAP - the work done to support .NET standard is really appreciated.

In regards to Normalizer2 API there are no current plans to support this since we don't need it for our other projects, but contributions are welcome. Just create a PR. I realize there's no document outlining the guidelines for contributing, but there probably should. Thanks for pointing that out.

**Comment by NightOwl888** [comment]
Thanks for replying. Just out of curiosity, have you tried using the C# wrapper generator here: http://site.icu-project.org/related? Seems like it could save a lot of the grunt work. Although, since we are trying to replace icu4j, we would need some wrappers around it to make it object-oriented.

**Comment by ermshiperete** [comment]
Version 2.5.0 partially implements Normalizer2 API.
