### ISSUE TITLE
Create/upload a NuGet package

### ISSUE THREAD

**Issue by conniey** [sillsdev/icu-dotnet#7]
I am working a on C# project that utilises ICU4C and it would be a lot easier to integrate this library in my project if I can consume it as a nuget package.

I was wondering if there are any plans to:
* Create a nupkg from the library 
* Upload the nuget package to a nuget feed (ie. https://www.nuget.org/ or https://myget.org)

I have done the work (to package this library as a nuget pkg) on a private branch but am wondering how to incorporate it in your build if your team wants this feature (or just upload a single package to a nuget feed).

Thanks,
Connie

**Comment by ermshiperete** [comment]
Yes, that sounds very useful.

It would have to be a nuget v2 package though since on Linux we use MonoDevelop which can't yet handle nuget v3.

I haven't looked into the differences between v2 and v3 (other than that they're not backwards compatible), so I don't know if there are situations where one would need both v2 and v3 packages. If so we could create a separate branch for v3.

I'm not sure yet if we'd want to automatically upload the nuget packages to nuget.org or myget.org for each build, or occasionally do a release and upload the nuget package manually.

It would be great if you'd create a PR with what you have!

**Comment by ermshiperete** [comment]
Nuget packages are now available at [nuget.org](https://www.nuget.org/packages/icu.net/)
