### ISSUE TITLE
2.3.4 throwing System.AccessViolationException

### ISSUE THREAD

**Issue by funex** [sillsdev/icu-dotnet#81]
Randomly I get the following exception:

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Icu.NativeMethods.ubrk_next(IntPtr)
   at Icu.RuleBasedBreakIterator.SetText(System.String)

## To Reproduce
Cannot reproduce it locally.
This has been an issue on earlier versions as discussed at https://github.com/sillsdev/icu-dotnet/issues/56

## Environment

- OS: Windows Server 2012R2 64 bit
- icu.net 2.3.4 with Icu4c.Win.Full.Lib 56.1.0
- Framework Version: v4.0.30319

**Comment by funex** [comment]
Out of curiosity, should I call Wrapper.Init() in the latest releases?

**Comment by funex** [comment]
The original description of the issue still remains, wrapper.Init() and Cleanup() didn't help.

**Comment by emrobinson** [comment]
I'm seeing the same exception in the same location. I'm trying to create a set of steps to reproduce, but finding it difficult. 

OS: Windows 10 Enterprise
icu.net: 2.5.1 with Icu4cWin.Full.Lib v59.1.15
Framework Version: v4.0.30319

**Comment by funex** [comment]
> I'm seeing the same exception in the same location. I'm trying to create a set of steps to reproduce, but finding it difficult.
> 
> OS: Windows 10 Enterprise
> icu.net: 2.5.1 with Icu4cWin.Full.Lib v59.1.15
> Framework Version: v4.0.30319

Same thing with me, I haven't figured out how to reproduce it.

**Comment by emrobinson** [comment]
Just looking at the code, I **think** I know what might be going on. 

From [here](https://docs.microsoft.com/en-us/dotnet/framework/interop/copying-and-pinning):  "As an optimization when either string type is marshaled by value (such as a Unicode character string), the marshaler passes the callee a direct pointer to managed strings in the internal Unicode buffer instead of copying it to a new buffer."

In RuleBreakerIterator.cs, SetText method lines 410 - 466:
* Calls ubrk_setText(..)  // passing pointer to the string internal buffer
* Then calls ubrk_first(..) and ubrk_next(...) until done.

It's possible that garbage collection happens in the managed code and relocates the Text string -- which would invalidate the pointer being passed (and held) by ubrk_setText(...) and would cause problems for subsequent calls to ubrk_next(...). (Unless icu4c is making a copy of the string -- which would be inefficient). 

I'm using the Nuget version of icu.net and not building the project directly. Anyone who's building directly should be able to test my assertions.
